PLAYER_NAME_FONT = "Arial"
PLAYER_NAME_SIZE = 14
PLAYER_NAME_WEIGHT = 400

RAGE_FONT_NAME = "Arial"
RAGE_FONT_SIZE = 24
RAGE_FONT_WEIGHT = 700
RAGE_FONT_COLOR = 0xBFFFFFFF                # white
RAGE_RESET_STRING = "-------------"

AMMO_COUNTER_MARGIN_RIGHT = 200
AMMO_COUNTER_MARGIN_BOTTOM = 12
AMMO_COUNTER_BACK_OFFSET = 2
AMMO_COUNTER_BACK_COLOR = 0xE0000000
AMMO_COUNTER_TEXT_COLOR = 0xE0CFCF7F
AMMO_COUNTER_FONT_NAME = "Arial"
AMMO_COUNTER_FONT_SIZE = 24
AMMO_COUNTER_FONT_WEIGHT = 700

KILLSTREAK_FONT = "Arial"
KILLSTREAK_SIZE = 80
KILLSTREAK_WEIGHT = 700

C4AUTOFIRE_FONT_NAME = "Arial"
C4AUTOFIRE_FONT_SIZE = 24
C4AUTOFIRE_FONT_WEIGHT = 700    # bold
C4AUTOFIRE_FONT_COLOR = 0xE0DFBF00

GRENADECOOKING_FONT_NAME = "Arial"
GRENADECOOKING_FONT_SIZE = 24
GRENADECOOKING_FONT_WEIGHT = 700    # bold
GRENADECOOKING_FONT_COLOR = 0xE0DF3F00
GRENADECOOKING_CENTER_Y = 20
GRENADECOOKING_TIMER = 4.7

KILLSTREAK_FONT_NAME = "Arial"
KILLSTREAK_FONT_SIZE = 80
KILLSTREAK_FONT_WEIGHT = 700    # bold
KILLSTREAK_FONT_COLOR = 0x5FFFFFFF  # grey

